### ISSUE TITLE
UI Tasks

### ISSUE THREAD

**Issue by mobile-bungalow** [kalix-systems/herald#1]
This is a general issue for UI tasks which anyone can grab and implement.

- [x] **Configuration Menu**
Description : Add a gear icon button on the first toolbar in the contacts pane. Upon clicking this icon should launch a configuration popup with options for.
    - [x] Name
    - [x] Profile Picture (Optional)
    - [x] UserID (Temporary placeholder)

- [x] **Chat View**
     - [x] Should render name and avatar of contact at the top of message view
     - [x] Should Display splash if no user is currently selected
     - [x] Should display splash screen if currently selected contact is deleted
     - [ ] <s> Emoji, Attatchment, and Audio message buttons by the text entry area. </s>*

*moved to sprint 2 electric boogaloo

- [X] **Side Bar**
     - [x] Search button
     - [x] Render username when it changes

- [x] **Contact Chat Selection**
Description : Clicking on a contact in the contact section should open a chatview with the relevant conversationID or UserID. 

- [x] **Visual Scaling Improvements**
    - [x] Currently there is no minimum window size
    - [x] we would like the contactsView to take up the entire screen when below a certain threshold screenwidth. 
    - [x] Padding at the top of all the messages that doesn't look horrible
    - [x] Scroll bar should be fixed size for each window size

- [x] **Refactors**
    - [x] Refactor all colors to global properties of the window which can be set in a config if necessary. 
    - [x] Refactor all anchors such that they only reference the anchor object once instead of serially.

- [x] **Polish**
    - [x] Color hashing from the global color scheme for contacts
    - [x] Chatview polish. put the chatbar in a rectangle. 
    - [ ]  <s>Animated (tasteful) transitions.</s>

**Comment by BaeoMaltinsky** [comment]
The current QML situation is a bit unwieldy. Let's try to factor components out into their own files and arrange things with folders.
