### ISSUE TITLE
Replace "property var" pattern for libherald types with explicit types

### ISSUE THREAD

**Issue by BaeoMaltinsky** [kalix-systems/herald#110]
Previously we were registered most of our types anonymously to prevent accidental creation that could be caught at compile time, but registering them as uncreatable gives us better tooling integration (at the cost of moving some errors to runtime). It's the right trade off to make, but we should be taking fuller advantage of it.

**Comment by kaavyajayram** [comment]
Pretty sure I caught most of them, fix more if you notice any
