### ISSUE TITLE
conversation ID's

### ISSUE THREAD

**Issue by GallagherCommaJack** [kalix-systems/herald#15]
We need them to be distinct from userid's in order to associate ratchet keys with (sender, conversation) pairs. This is probably going to change a bunch of things involving the DB, and then a few message types.

Baeo, assigning this to you since AFAIK client-side DB stuff is your wheelhouse. Reassign it if this isn't true.

**Comment by BaeoMaltinsky** [comment]
Database work is mostly done on the libherald branch. It cannot be merged into master until figuring out the what the public API needs to be.

**Comment by mobile-bungalow** [comment]
This is closed, no?

**Comment by BaeoMaltinsky** [comment]
Not yet merged to master.

**Comment by BaeoMaltinsky** [comment]
And now it has
