### ISSUE TITLE
Clarify scope of various sub-projects

### ISSUE THREAD

**Issue by BaeoMaltinsky** [kalix-systems/herald#16]
We have been following a heuristic to decide which functionality belongs in heraldcore, but I think it's worth discussing what exactly each sub-project is for. My understanding was that herald_common was mostly to keep type definitions in sync between the client and server, but there seem to be a number of types (such as the message status enums) that are only of interest to the client.

Should we create a page on the wiki documenting project scope?

**Comment by GallagherCommaJack** [comment]
1) Common should just be for common types and functionality. If something is only useful to the client (e.g. message status) it belongs in core.
2) Wiki page seems appropriate.
