### ISSUE TITLE
Features List

### ISSUE THREAD

**Issue by kaavyajayram** [kalix-systems/herald#2]
Running list of features we want now or eventually or maybe (everyone shld add stuff)

Wants:
- [x] Reacts of any emoji
- [x] Color schemes
- [ ] Markdown in texts
- [x] Read receipts

Maybe:
- [ ] Typing indicators
- [ ] Reminders
- [ ] Polls
- [ ] LaTeX in texts

**Comment by GallagherCommaJack** [comment]
I think editing messages is a misfeature, though editing pinned content in teams might make sense.

**Comment by BaeoMaltinsky** [comment]
> I think editing messages is a misfeature, though editing pinned content in teams might make sense.

Well, not necessarily. It's not too difficult to just store the full revision history. I think there's value in allowing people to fix typos.
