### ISSUE TITLE
running list of tasks

### ISSUE THREAD

**Issue by kaavyajayram** [kalix-systems/herald#20]
this list is not complete

**Things to do:**
Contacts
  - [x] adding a new contact should be a new view of the right pane 
  - [x] renaming contacts should probably also be a different popup
  - [x] bulk selection/deletion of contacts

Messages
   - [x] add replies
   - [x] message deletion
   - [x] open a view with extra information abt messages (time read, time sent)

**Things that are borked:**
- [x] Reply button hitbox should be adjusted
- [x] when a contact is deleted if a contact is being viewed the conversation_id should be set to that viewed contact immediately
- [x] contacts search doesn't work until restart
- [x] splash screen should not instantiate if contact deleted is not one currently being viewed

**Comment by mobile-bungalow** [comment]
Might be a good Idea to move this into projects.
