### ISSUE TITLE
On branch fusion, contact archival will flicker the entire application to black %50 of the time

### ISSUE THREAD

**Issue by mobile-bungalow** [kalix-systems/herald#26]
The bug can be observed in commits after 7c57ebd760dc. It is likely not a performance issue, as removing the heftier parts of the deleteContact function in ContactClickedPopup.mjs did not solve any issues.

**Comment by BaeoMaltinsky** [comment]
Firstly, you are talking about *deletion*, not *archival*.

Secondly, I cannot seem toreproduce the behaviour on Linux. Can you describe the steps I should follow in more detail?

**Comment by mobile-bungalow** [comment]
Issue is specific to OSX. Not present on master. simply add and delete any contact.

**Comment by kaavyajayram** [comment]
fixed: osx borks if you load windows in places other than main, don't do it
