### ISSUE TITLE
Make conversations sorted by last sent message & contacts sort alphabetically

### ISSUE THREAD

**Issue by kaavyajayram** [kalix-systems/herald#33]

**Comment by BaeoMaltinsky** [comment]
What do you mean by sort contacts alphabetically? They have user ids and sometimes names. Do you want them sorted by display name?

**Comment by kaavyajayram** [comment]
I think for contacts display name makes the most sense. (so, name and defaults to user ID if no name)

I can't think of a time we would want to sort contacts another way, being able to also sort conversations alphabetically seems useful in a couple cases

**Comment by BaeoMaltinsky** [comment]
It is done.
