### ISSUE TITLE
Bug: Reassigning a Contact name temporarily sets the name in the ContactBar as well.

### ISSUE THREAD

**Issue by mobile-bungalow** [kalix-systems/herald#4]
Desired behavior: upon renaming a contact, the name at the top of the chatview, in the chatbar should change iff you are in chatting with the renamed contact.

Current behavior: The name in the chatbar changes temporarily to the new name of any contact that has had its name edited.

**Comment by BaeoMaltinsky** [comment]
Pushed a hot fix
