### ISSUE TITLE
Use appropriate data directories on iOS and Android

### ISSUE THREAD

**Issue by BaeoMaltinsky** [kalix-systems/herald#46]
Currently, heraldcore uses the appropriate data directories on desktop platforms in the `platform_dirs` module.

There are implementations for Android and iOS, but they are placeholders and currently just use whatever `$PWD` Android and iOS happen to pass them. I believe there are well-defined (or at least, strongly suggested) application specific data directories on these platforms, but have not looked into exactly what they are.

**Comment by BaeoMaltinsky** [comment]
One solution for this may to just lean on Qt for this, as they've already [done the work for us](https://doc.qt.io/qt-5/qstandardpaths.html) as just initialize it [from QML](https://doc.qt.io/qt-5/qml-qt-labs-platform-standardpaths.html) using something like [`once_cell`](https://docs.rs/once_cell/1.2.0/once_cell/). Very plausibly we should just do this on every platform and drop the `directories` dependency, but I like being able to make `heraldcore` more self contained on desktop platforms.

**Comment by mobile-bungalow** [comment]
for future reference: 
iOS should place user generated data in [<Application root>/Library/Caches](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html). Putting any files in /Documents is a security oversight.
Android should avoid using the media cache api, and just use the local file system for security reasons as well.

**Comment by BaeoMaltinsky** [comment]
Sure, but that's relative to the root of the app bundle. I'd prefer to use an absolute path instead of walking the directory from the binary, hence the desire to lean on Qt to get the paths.
