### ISSUE TITLE
Disappearing timer changes in message history

### ISSUE THREAD

**Issue by BaeoMaltinsky** [kalix-systems/herald#47]
I'm inclined to make this a UI detail rather than a persistent feature of a linear message history. If you have secrets worth hiding, then not having a record of having turned them on or off seems correct.

If we go this route, this can stay confined to `libherald`, if we don't and make them persistent, then there are a number of questions I would like to have answered about how these are going to be handled (e.g., are these events searchable in the global message search).

**Comment by GallagherCommaJack** [comment]
Any persistent record of deleted messages is something we should avoid wherever possible.

**Comment by colleenm** [comment]
Agree with Jack, I prefer no record in message history.

I don't know what "make this a UI detail means"--do you mean we only show what the current timer setting is set to somewhere in the client UI? (That's what I think we should do)

**Comment by kaavyajayram** [comment]
++ Changes regarding expiring message disappear with the messages
