### ISSUE TITLE
Call catch_panic in libherald public api

### ISSUE THREAD

**Issue by GallagherCommaJack** [kalix-systems/herald#53]
Panicking across ffi is undefined behavior. Since we almost certainly won't succeed in proving the code won't panic, we should just catch it.

**Comment by BaeoMaltinsky** [comment]
An easy fix for this is modifying the codegen to catch unwinding panics. If it comes to that I'm inclined to think the program should just crash, so this really just be for cases where we really can't just propagate or handle an error.
