### ISSUE TITLE
user display name, avatar, timestamp removed when first message in flurry is deleted

### ISSUE THREAD

**Issue by colleenm** [kalix-systems/herald#75]
observed behavior:
- send many messages as a flurry
- delete first message
- notice flurry no longer has avatar, display name, timestamp at top

correct behavior:
- send many messages as a flurry
- delete first message
- avatar and display name should persist; timestamp should update to be the timestamp of the first non-deleted message in the flurry

probably means name/avatar need to be associated with a thing besides the message itself

(Kaavya, assigning to you because I know you're doing chat bubble stuff and I don't know whether anyone actually reviews the bug list for new things, unassign from yourself if that is more correct)

**Comment by BaeoMaltinsky** [comment]
Fixed
