### ISSUE TITLE
On desktop, the reply pop up offsets the bottom of the chat listview.

### ISSUE THREAD

**Issue by mobile-bungalow** [kalix-systems/herald#83]
Platform:
MacOs 10.14

steps to reproduce:
1. Login and open a note to self conversation.
2. Send a few messages
3. Press reply and send.

Results:
The lowest part of the chat listview does not drop to the bottom of its intended area until the window is resized. It hangs where the previous reply dialog had been.

Desired Results: 
The list view should return to its anchored position immediately upon sending the reply.

**Comment by kaavyajayram** [comment]
Fixed
