### ISSUE TITLE
Use consistent names for similar properties across different models in libherald

### ISSUE THREAD

**Issue by kaavyajayram** [kalix-systems/herald#94]
eg profilePicture everywhere, not profilePicture and sometimes picture

**Comment by BaeoMaltinsky** [comment]
Is it correct to call conversation pictures "profile pictures"?

**Comment by kaavyajayram** [comment]
@BaeoMaltinsky No, probably not - we might want to just call them all 'picture'

**Comment by kaavyajayram** [comment]
I care less about the property exactly matching the thing its for and more about the property being the same everywhere, because that makes things easier to remember. so picture everywhere seems fine
